service: yrtt-tasks-backend-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  region: eu-west-2
  profile: serverless
package:
  artifact: target/tasks-api-java-dev.jar

functions:
  get-tasks-java-api:
    handler: com.techreturners.GetTasksHandler
    events:
      - http:
          path: /users/{userId}/tasks
          method: get
  save-task-java-api:
    handler: com.techreturners.SaveTaskHandler
    events:
      - http:
          path: /users/{userId}/tasks
          method: post
