service: yrtt-tasks-backend-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  region: eu-west-2
  profile: serverless
package:
  artifact: target/hello-dev.jar

functions:
  tasks-api:
    handler: com.techreturners.Handler
    events:
      - http:
          path: tasks
          method: get
